import React from 'react'
import './Footer2.css';


const Footer2 = () => {
  return (
    <div className='footer-container2'>
      <div className='footer-links2'>
        <h1>Generated by The Kairos Family</h1>
        <h2>2024, Crowned Naturally, All Rights Reserved</h2>
        <div className='footer-sections2'>
          <ul>
            <h2>Contact Us</h2>
            <li>Number</li>
            <li>E-mail</li>
            <li>Location with icon</li>
          </ul>
          <ul>
            <h2>Important Links</h2>
            <li>Home</li>
            <li>About Us</li>
            <li>All Products</li>
            <li>Contact Us</li>
          </ul>
          <ul>
            <h2>Connect With Us</h2>
            <li>IG icon</li>
            <li>General link</li>
            <li>LinkedIn</li>
          </ul>
        </div>
      </div>
    </div>
  )
}

export default Footer2